version: "3.5"
services:
  reth:
    build:
      context: reth
      args:
        UPSTREAM_VERSION: v1.0.2
        STAKER_SCRIPTS_VERSION: v0.1.0
    volumes:
      - reth:/data/reth
    environment:
      EXTRA_OPTS: null
    restart: unless-stopped
volumes:
  reth: {}
