version: "3.5"
services:
  reth:
    build:
      context: reth
      args:
        UPSTREAM_VERSION: v1.3.10
        STAKER_SCRIPTS_VERSION: v0.1.2
        DATA_DIR: /data/reth
    volumes:
      - reth:/data/reth
    environment:
      RPC_MAX_BLOCKS_PER_FILTER: "0"
      EXTRA_OPTS: null
      ARCHIVE_NODE: "false"
    restart: unless-stopped
volumes:
  reth: {}
