version: "3.5"
services:
  reth:
    build:
      context: reth
      args:
        UPSTREAM_VERSION: v1.1.0
        STAKER_SCRIPTS_VERSION: v0.1.0
        DATA_DIR: /data/reth
    volumes:
      - reth:/data/reth
    environment:
      EXTRA_OPTS: null
      ARCHIVE_NODE: false
    restart: unless-stopped
volumes:
  reth: {}
